quizapplication:
  passingscore: 3
  filepath: C:\Users\Admin\Desktop\OtusSpringHomeWork\hw3-boot\src\main\resources\HW1-IoC.csv
  numberOfQuestion: 5
spring:
  banner:
    location: banner/banner.txt
  messages:
    basename: i18n/messages
