server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      database: library
  webflux:
    base-path: /

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw11webflux.changelog